// test/unit/e2e/apiRouteContract.test.mjs — the C installer's /api route +
// session-token gate contract, checked STATICALLY against
// test/e2e/installer/apiRoutes.mjs.
//
// Why this exists: the security smoke test (test/e2e/installer/smoke-security.mjs)
// needs a built installer binary, so it only runs in the E2E job — and its route
// lists were hand-maintained. A route added to installer/src/main.c without a
// matching entry would silently escape the security smoke test entirely. This
// test parses the C sources instead, so plain `pnpm test` fails the moment C
// reality and the classified sets diverge.
//
// The parse is deliberately shallow but exact for the two things that matter:
// the `http_server_register()` table (the only place routes are declared) and
// whether each handler's body calls the token gate.

import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('../../..', import.meta.url));
const SRC_DIR = path.join(REPO_ROOT, 'installer', 'src');
const API_PREFIX = '/api/';

const routesUrl = pathToFileURL(
  path.join(REPO_ROOT, 'test', 'e2e', 'installer', 'apiRoutes.mjs')
).href;
const {
  GATED_API_ROUTES,
  OPEN_API_ROUTES,
  SHUTDOWN_API_ROUTE,
  SHUTDOWN_REJECT_BODY,
  TOKEN_REFLECTING_API_ROUTE,
  UNAUTHORIZED_REJECT_BODY,
} = await import(routesUrl);

/** The C helper every gated handler must call. */
const TOKEN_GATE = 'request_has_valid_token';

// ── Parsing ──────────────────────────────────────────────────────────────────

/**
 * Every top-level `.c` in installer/src, CRLF-normalized (tracked text files
 * are LF). The helper/ subdirectory is excluded: those are the elevated-copy
 * helpers and serve no HTTP routes.
 *
 * @returns {Map<string, string>} file name → source text
 */
function readSources() {
  const sources = new Map();
  for (const name of fs.readdirSync(SRC_DIR).sort()) {
    if (!name.endsWith('.c')) continue;
    sources.set(name, fs.readFileSync(path.join(SRC_DIR, name), 'utf8').replaceAll('\r\n', '\n'));
  }
  return sources;
}

/**
 * The route table: `http_server_register("/api/x", handle_api_x);`.
 *
 * @param {Map<string, string>} sources
 * @returns {Map<string, {handler: string; file: string}>} route path → handler
 */
function registeredRoutes(sources) {
  const routes = new Map();
  const re = /http_server_register\(\s*"([^"]+)"\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)/g;
  for (const [file, text] of sources) {
    for (const m of text.matchAll(re)) {
      routes.set(m[1], {handler: m[2], file});
    }
  }
  return routes;
}

/**
 * Handler name → its body text.
 *
 * A body runs from its definition to the next definition in the same file. No
 * brace matching: the bodies contain braces inside JSON string literals
 * (`"{\"error\":\"unauthorized\"}"`), which makes naive brace counting wrong.
 * The definition regex requires the opening `{`, so prototype declarations
 * (`...);`) are not mistaken for bodies. Static-asset handlers are generated by
 * the `DEFINE_GZ_HANDLER` macro and never serve an /api route, so they need no
 * entry here.
 *
 * @param {Map<string, string>} sources
 * @returns {Map<string, string>} handler name → body text
 */
function handlerBodies(sources) {
  const bodies = new Map();
  // Anchored, single-line signature match over our own C sources (never
  // untrusted input) — the unsafe-regex warning is a false positive.
  // eslint-disable-next-line security/detect-unsafe-regex
  const defRe = /^(?:static\s+)?(?:int|void)\s+(handle_[A-Za-z0-9_]+)\s*\([^;{]*\)\s*\{/gm;
  for (const text of sources.values()) {
    const defs = [...text.matchAll(defRe)];
    defs.forEach((match, i) => {
      const end = i + 1 < defs.length ? defs[i + 1].index : text.length;
      bodies.set(match[1], text.slice(match.index, end));
    });
  }
  return bodies;
}

const sources = readSources();
const registered = registeredRoutes(sources);
const bodies = handlerBodies(sources);

const apiRoutes = [...registered]
  .filter(([routePath]) => routePath.startsWith(API_PREFIX))
  .map(([routePath, {handler, file}]) => ({
    name: routePath.slice(API_PREFIX.length),
    handler,
    file,
    body: bodies.get(handler),
  }));
const byName = new Map(apiRoutes.map(route => [route.name, route]));

const CLASSIFIED = [
  ...GATED_API_ROUTES,
  SHUTDOWN_API_ROUTE,
  TOKEN_REFLECTING_API_ROUTE,
  ...OPEN_API_ROUTES,
];

/** Every registered /api route whose handler calls the session-token gate. */
const gatedInC = apiRoutes
  .filter(route => (route.body ?? '').includes(TOKEN_GATE))
  .map(route => route.name)
  .sort();

// ── Parser sanity: never pass by parsing nothing ──────────────────────────────

test('apiRouteContract: the route table and every handler body parse', () => {
  assert.ok(
    registered.size > CLASSIFIED.length,
    `parsed only ${registered.size} routes from installer/src — the route table regex has drifted`
  );
  assert.ok(
    [...registered.keys()].some(routePath => !routePath.startsWith(API_PREFIX)),
    'expected the static-asset routes in the same route table'
  );
  // A blind parser is the one failure mode that would make every check below
  // vacuously pass, so assert each named handler resolved to a real body.
  const unresolved = apiRoutes.filter(route => !route.body).map(route => route.handler);
  assert.deepEqual(unresolved, [], 'handler bodies not found for these handlers');
  // The gate helper itself must still exist under this name; otherwise the
  // `gatedInC` filter would just find nothing.
  assert.match(
    [...sources.values()].join('\n'),
    /static\s+int\s+request_has_valid_token\s*\(\s*const\s+char\s*\*\s*query\s*\)/,
    `installer/src no longer defines ${TOKEN_GATE}()`
  );
});

// ── Coverage: nothing escapes the classification ─────────────────────────────

test('apiRouteContract: every registered /api route is classified exactly once', () => {
  assert.equal(
    new Set(CLASSIFIED).size,
    CLASSIFIED.length,
    'a route appears in more than one of the gated/shutdown/claim/open sets'
  );

  const unclassified = apiRoutes
    .map(route => route.name)
    .filter(name => !CLASSIFIED.includes(name))
    .sort();
  assert.deepEqual(
    unclassified,
    [],
    'route(s) registered in installer/src but absent from test/e2e/installer/apiRoutes.mjs'
  );

  const stale = CLASSIFIED.filter(name => !byName.has(name)).sort();
  assert.deepEqual(
    stale,
    [],
    'route(s) listed in apiRoutes.mjs but no longer registered in installer/src'
  );
});

// ── The gate itself ──────────────────────────────────────────────────────────

test('apiRouteContract: the C token gate matches the gated set exactly', () => {
  assert.deepEqual(
    gatedInC,
    [...GATED_API_ROUTES].sort(),
    `${TOKEN_GATE}() call sites do not match GATED_API_ROUTES`
  );
});

test('apiRouteContract: every gated handler returns the body the smoke test looks for', () => {
  for (const name of GATED_API_ROUTES) {
    const route = byName.get(name);
    assert.ok(route?.body, `/api/${name}: handler body not found`);
    assert.ok(
      route.body.includes(UNAUTHORIZED_REJECT_BODY),
      `/api/${name} (${route.handler} in ${route.file}) must answer a bad token with "${UNAUTHORIZED_REJECT_BODY}"`
    );
  }
});

// ── The two special cases ────────────────────────────────────────────────────

test('apiRouteContract: the token-reflecting route reflects instead of rejecting', () => {
  const route = byName.get(TOKEN_REFLECTING_API_ROUTE);
  assert.ok(route?.body, `/api/${TOKEN_REFLECTING_API_ROUTE}: handler body not found`);
  assert.match(
    route.body,
    /\\"current\\"/,
    `/api/${TOKEN_REFLECTING_API_ROUTE} must report "current" (the smoke test asserts current:0/1)`
  );
  assert.match(
    route.body,
    /g_session_token|installer_session_token/,
    `/api/${TOKEN_REFLECTING_API_ROUTE} must compare against the current run's token`
  );
  assert.ok(
    !route.body.includes(TOKEN_GATE) && !route.body.includes(UNAUTHORIZED_REJECT_BODY),
    `/api/${TOKEN_REFLECTING_API_ROUTE} must never reject — it reflects validity`
  );
});

test('apiRouteContract: the shutdown route is gated, but silently', () => {
  const route = byName.get(SHUTDOWN_API_ROUTE);
  assert.ok(route?.body, `/api/${SHUTDOWN_API_ROUTE}: handler body not found`);
  assert.match(
    route.body,
    /installer_session_token/,
    `/api/${SHUTDOWN_API_ROUTE} must validate the caller's token`
  );
  assert.ok(
    route.body.includes(SHUTDOWN_REJECT_BODY),
    `/api/${SHUTDOWN_API_ROUTE} must return the "${SHUTDOWN_REJECT_BODY}" body for a stale/missing token`
  );
  assert.ok(
    !route.body.includes(TOKEN_GATE) && !route.body.includes(UNAUTHORIZED_REJECT_BODY),
    `/api/${SHUTDOWN_API_ROUTE} must not use the ${TOKEN_GATE}() error path — it is ignored, not refused`
  );
});

// ── Open routes carry no token machinery at all ──────────────────────────────

test('apiRouteContract: open routes are readable without a token', () => {
  for (const name of OPEN_API_ROUTES) {
    const route = byName.get(name);
    assert.ok(route?.body, `/api/${name}: handler body not found`);
    for (const marker of [TOKEN_GATE, 'installer_session_token', UNAUTHORIZED_REJECT_BODY]) {
      assert.ok(
        !route.body.includes(marker),
        `/api/${name} (${route.handler} in ${route.file}) is in OPEN_API_ROUTES but references ${marker}`
      );
    }
  }
});

// ── Localhost request contract ─────────────────────────────────────────────
//
// The three divergent `t=` parsers (request_has_valid_token, /api/claim,
// /api/shutdown) stay collapsed into one query_param_equals() helper, and
// /api/claim must not answer current:1 without a token. The serve loop must
// refuse a foreign Host/Origin before routing. An upload is verified against
// the manifest before it is stored, and a candidate manifest is checked
// against the stored zips before it is ingested.
//
// These are static checks — `pnpm test` has no C compiler. The SEMANTIC cases
// (?t=<tok>&x=1, ?xt=<tok>, no-token claim, foreign Host/Origin) run against
// the real binary in test/e2e/installer/smoke-security.mjs.

/**
 * Body of a named function from any installer/src top-level `.c` file, sliced
 * from its definition to the next definition in the same file — the same rule
 * handlerBodies() uses (see its comment for why no brace matching).
 *
 * @param {string} name
 * @returns {string} the definition text, or '' when the function is absent
 */
function functionBody(name) {
  // Anchored, single-line signature match over our own C sources (never
  // untrusted input) — the unsafe-regex warning is the same false positive
  // as the one on handlerBodies()' defRe above.
  // eslint-disable-next-line security/detect-unsafe-regex
  const defRe = /^(?:static\s+)?(?:int|void)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\([^;{]*\)\s*\{/gm;
  for (const text of sources.values()) {
    const defs = [...text.matchAll(defRe)];
    const i = defs.findIndex(d => d[1] === name);
    if (i >= 0) {
      const end = i + 1 < defs.length ? defs[i + 1].index : text.length;
      return text.slice(defs[i].index, end);
    }
  }
  return '';
}

test('apiRouteContract: one query_param_equals() serves every token parse', () => {
  const all = [...sources.values()].join('\n');
  assert.equal(
    (all.match(/^int query_param_equals\(/gm) ?? []).length,
    1,
    'installer/src must define query_param_equals() exactly once'
  );
  assert.ok(
    !all.includes('strstr(query, "t=")'),
    'the raw t= parsers are gone — every token parse routes through query_param_equals()'
  );

  const gate = functionBody('request_has_valid_token');
  assert.match(
    gate,
    /query_param_equals\(\s*query\s*,\s*"t"/,
    'request_has_valid_token() must compare through query_param_equals()'
  );

  const claim = functionBody('handle_api_claim');
  assert.match(
    claim,
    /query_param_equals\(\s*query\s*,\s*"t"/,
    '/api/claim must compare through query_param_equals()'
  );
  assert.ok(
    !/is_current\s*=\s*1\b/.test(claim),
    '/api/claim must not default to current:1 — no token means current:0'
  );
  assert.ok(
    claim.includes('\\"current\\"'),
    '/api/claim still reports "current" (the smoke test asserts current:0/1)'
  );

  const shutdown = functionBody('handle_api_shutdown');
  assert.match(
    shutdown,
    /query_param_equals\(\s*query\s*,\s*"t"/,
    '/api/shutdown must compare through query_param_equals()'
  );
});

test('apiRouteContract: the serve loop refuses a foreign Host/Origin', () => {
  const src = sources.get('http_server.c');
  assert.match(
    src,
    /static\s+int\s+host_origin_allowed\s*\(/,
    'http_server.c must define host_origin_allowed()'
  );
  const checkBody = functionBody('host_origin_allowed');
  assert.match(checkBody, /"host"/, 'the check inspects the Host header');
  assert.match(checkBody, /"origin"/, 'the check inspects the Origin header');
  assert.ok(
    checkBody.includes('localhost:%u') && checkBody.includes('127.0.0.1:%u'),
    'only localhost:<port> / 127.0.0.1:<port> carrying the bound port are allowed'
  );

  const serve = functionBody('http_server_serve');
  const checked = serve.indexOf('host_origin_allowed(');
  const routed = serve.indexOf('find_handler(');
  assert.ok(checked >= 0, 'the serve loop calls host_origin_allowed()');
  assert.ok(routed >= 0 && checked < routed, 'validation runs before routing');
  assert.match(serve, /403/, 'a refused request is answered 403');
});

test('apiRouteContract: uploads are verified against the manifest', () => {
  // Both verifiers live in the manifest module since detect_browser.c was
  // split; pin them there so a move to an unexpected file
  // still fails.
  const manifestModule = sources.get('manifest.c');
  assert.match(
    manifestModule,
    /^int installer_verify_upload\(/m,
    'manifest.c must define installer_verify_upload()'
  );
  assert.match(
    manifestModule,
    /^int installer_verify_stored_zips\(/m,
    'manifest.c must define installer_verify_stored_zips()'
  );

  const upload = functionBody('handle_api_upload');
  const verified = upload.indexOf('installer_verify_upload(');
  const stored = upload.indexOf('installer_set_uploaded_zip(');
  assert.ok(
    verified >= 0,
    'the upload handler verifies candidate bytes when the manifest is known'
  );
  assert.ok(stored >= 0 && verified < stored, 'verification runs before the zip is stored');

  const manifest = functionBody('handle_api_manifest');
  const vAt = manifest.indexOf('installer_verify_stored_zips(');
  const iAt = manifest.indexOf('ingest_remote_manifest(');
  assert.ok(vAt >= 0, 'the manifest handler verifies stored zips against the candidate manifest');
  assert.ok(iAt >= 0 && vAt < iAt, 'verification runs before ingest');
});
