// test/unit/e2e/apiRouteContract.test.mjs — the C installer's /api route +
// session-token gate contract, checked STATICALLY against
// test/e2e/installer/apiRoutes.mjs.
//
// Why this exists: the security smoke test (test/e2e/installer/smoke-security.mjs)
// needs a built installer binary, so it only runs in the E2E job — and its route
// lists were hand-maintained. A route added to installer/src/main.c without a
// matching entry would silently escape the security smoke test entirely. This
// test parses the C sources instead, so plain `pnpm test` fails the moment C
// reality and the classified sets diverge (issue #30-adjacent; flagged by the
// 2026-09-15 audit).
//
// The parse is deliberately shallow but exact for the two things that matter:
// the `http_server_register()` table (the only place routes are declared) and
// whether each handler's body calls the token gate.

import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('../../..', import.meta.url));
const SRC_DIR = path.join(REPO_ROOT, 'installer', 'src');
const API_PREFIX = '/api/';

const routesUrl = pathToFileURL(
  path.join(REPO_ROOT, 'test', 'e2e', 'installer', 'apiRoutes.mjs')
).href;
const {
  GATED_API_ROUTES,
  OPEN_API_ROUTES,
  SHUTDOWN_API_ROUTE,
  SHUTDOWN_REJECT_BODY,
  TOKEN_REFLECTING_API_ROUTE,
  UNAUTHORIZED_REJECT_BODY,
} = await import(routesUrl);

/** The C helper every gated handler must call. */
const TOKEN_GATE = 'request_has_valid_token';

// ── Parsing ──────────────────────────────────────────────────────────────────

/**
 * Every top-level `.c` in installer/src, CRLF-normalized (tracked text files
 * are LF). The helper/ subdirectory is excluded: those are the elevated-copy
 * helpers and serve no HTTP routes.
 *
 * @returns {Map<string, string>} file name → source text
 */
function readSources() {
  const sources = new Map();
  for (const name of fs.readdirSync(SRC_DIR).sort()) {
    if (!name.endsWith('.c')) continue;
    sources.set(name, fs.readFileSync(path.join(SRC_DIR, name), 'utf8').replaceAll('\r\n', '\n'));
  }
  return sources;
}

/**
 * The route table: `http_server_register("/api/x", handle_api_x);`.
 *
 * @param {Map<string, string>} sources
 * @returns {Map<string, {handler: string; file: string}>} route path → handler
 */
function registeredRoutes(sources) {
  const routes = new Map();
  const re = /http_server_register\(\s*"([^"]+)"\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)/g;
  for (const [file, text] of sources) {
    for (const m of text.matchAll(re)) {
      routes.set(m[1], {handler: m[2], file});
    }
  }
  return routes;
}

/**
 * Handler name → its body text.
 *
 * A body runs from its definition to the next definition in the same file. No
 * brace matching: the bodies contain braces inside JSON string literals
 * (`"{\"error\":\"unauthorized\"}"`), which makes naive brace counting wrong.
 * The definition regex requires the opening `{`, so prototype declarations
 * (`...);`) are not mistaken for bodies. Static-asset handlers are generated by
 * the `DEFINE_GZ_HANDLER` macro and never serve an /api route, so they need no
 * entry here.
 *
 * @param {Map<string, string>} sources
 * @returns {Map<string, string>} handler name → body text
 */
function handlerBodies(sources) {
  const bodies = new Map();
  // Anchored, single-line signature match over our own C sources (never
  // untrusted input) — the unsafe-regex warning is a false positive.
  // eslint-disable-next-line security/detect-unsafe-regex
  const defRe = /^(?:static\s+)?(?:int|void)\s+(handle_[A-Za-z0-9_]+)\s*\([^;{]*\)\s*\{/gm;
  for (const text of sources.values()) {
    const defs = [...text.matchAll(defRe)];
    defs.forEach((match, i) => {
      const end = i + 1 < defs.length ? defs[i + 1].index : text.length;
      bodies.set(match[1], text.slice(match.index, end));
    });
  }
  return bodies;
}

const sources = readSources();
const registered = registeredRoutes(sources);
const bodies = handlerBodies(sources);

const apiRoutes = [...registered]
  .filter(([routePath]) => routePath.startsWith(API_PREFIX))
  .map(([routePath, {handler, file}]) => ({
    name: routePath.slice(API_PREFIX.length),
    handler,
    file,
    body: bodies.get(handler),
  }));
const byName = new Map(apiRoutes.map(route => [route.name, route]));

const CLASSIFIED = [
  ...GATED_API_ROUTES,
  SHUTDOWN_API_ROUTE,
  TOKEN_REFLECTING_API_ROUTE,
  ...OPEN_API_ROUTES,
];

/** Every registered /api route whose handler calls the session-token gate. */
const gatedInC = apiRoutes
  .filter(route => (route.body ?? '').includes(TOKEN_GATE))
  .map(route => route.name)
  .sort();

// ── Parser sanity: never pass by parsing nothing ──────────────────────────────

test('apiRouteContract: the route table and every handler body parse', () => {
  assert.ok(
    registered.size > CLASSIFIED.length,
    `parsed only ${registered.size} routes from installer/src — the route table regex has drifted`
  );
  assert.ok(
    [...registered.keys()].some(routePath => !routePath.startsWith(API_PREFIX)),
    'expected the static-asset routes in the same route table'
  );
  // A blind parser is the one failure mode that would make every check below
  // vacuously pass, so assert each named handler resolved to a real body.
  const unresolved = apiRoutes.filter(route => !route.body).map(route => route.handler);
  assert.deepEqual(unresolved, [], 'handler bodies not found for these handlers');
  // The gate helper itself must still exist under this name; otherwise the
  // `gatedInC` filter would just find nothing.
  assert.match(
    [...sources.values()].join('\n'),
    /static\s+int\s+request_has_valid_token\s*\(\s*const\s+char\s*\*\s*query\s*\)/,
    `installer/src no longer defines ${TOKEN_GATE}()`
  );
});

// ── Coverage: nothing escapes the classification ─────────────────────────────

test('apiRouteContract: every registered /api route is classified exactly once', () => {
  assert.equal(
    new Set(CLASSIFIED).size,
    CLASSIFIED.length,
    'a route appears in more than one of the gated/shutdown/claim/open sets'
  );

  const unclassified = apiRoutes
    .map(route => route.name)
    .filter(name => !CLASSIFIED.includes(name))
    .sort();
  assert.deepEqual(
    unclassified,
    [],
    'route(s) registered in installer/src but absent from test/e2e/installer/apiRoutes.mjs'
  );

  const stale = CLASSIFIED.filter(name => !byName.has(name)).sort();
  assert.deepEqual(
    stale,
    [],
    'route(s) listed in apiRoutes.mjs but no longer registered in installer/src'
  );
});

// ── The gate itself ──────────────────────────────────────────────────────────

test('apiRouteContract: the C token gate matches the gated set exactly', () => {
  assert.deepEqual(
    gatedInC,
    [...GATED_API_ROUTES].sort(),
    `${TOKEN_GATE}() call sites do not match GATED_API_ROUTES`
  );
});

test('apiRouteContract: every gated handler returns the body the smoke test looks for', () => {
  for (const name of GATED_API_ROUTES) {
    const route = byName.get(name);
    assert.ok(route?.body, `/api/${name}: handler body not found`);
    assert.ok(
      route.body.includes(UNAUTHORIZED_REJECT_BODY),
      `/api/${name} (${route.handler} in ${route.file}) must answer a bad token with "${UNAUTHORIZED_REJECT_BODY}"`
    );
  }
});

// ── The two special cases ────────────────────────────────────────────────────

test('apiRouteContract: the token-reflecting route reflects instead of rejecting', () => {
  const route = byName.get(TOKEN_REFLECTING_API_ROUTE);
  assert.ok(route?.body, `/api/${TOKEN_REFLECTING_API_ROUTE}: handler body not found`);
  assert.match(
    route.body,
    /\\"current\\"/,
    `/api/${TOKEN_REFLECTING_API_ROUTE} must report "current" (the smoke test asserts current:0/1)`
  );
  assert.match(
    route.body,
    /g_session_token|installer_session_token/,
    `/api/${TOKEN_REFLECTING_API_ROUTE} must compare against the current run's token`
  );
  assert.ok(
    !route.body.includes(TOKEN_GATE) && !route.body.includes(UNAUTHORIZED_REJECT_BODY),
    `/api/${TOKEN_REFLECTING_API_ROUTE} must never reject — it reflects validity`
  );
});

test('apiRouteContract: the shutdown route is gated, but silently', () => {
  const route = byName.get(SHUTDOWN_API_ROUTE);
  assert.ok(route?.body, `/api/${SHUTDOWN_API_ROUTE}: handler body not found`);
  assert.match(
    route.body,
    /installer_session_token/,
    `/api/${SHUTDOWN_API_ROUTE} must validate the caller's token`
  );
  assert.ok(
    route.body.includes(SHUTDOWN_REJECT_BODY),
    `/api/${SHUTDOWN_API_ROUTE} must return the "${SHUTDOWN_REJECT_BODY}" body for a stale/missing token`
  );
  assert.ok(
    !route.body.includes(TOKEN_GATE) && !route.body.includes(UNAUTHORIZED_REJECT_BODY),
    `/api/${SHUTDOWN_API_ROUTE} must not use the ${TOKEN_GATE}() error path — it is ignored, not refused`
  );
});

// ── Open routes carry no token machinery at all ──────────────────────────────

test('apiRouteContract: open routes are readable without a token', () => {
  for (const name of OPEN_API_ROUTES) {
    const route = byName.get(name);
    assert.ok(route?.body, `/api/${name}: handler body not found`);
    for (const marker of [TOKEN_GATE, 'installer_session_token', UNAUTHORIZED_REJECT_BODY]) {
      assert.ok(
        !route.body.includes(marker),
        `/api/${name} (${route.handler} in ${route.file}) is in OPEN_API_ROUTES but references ${marker}`
      );
    }
  }
});
