#!/usr/bin/env node
// tools/publish/generateBuildDates.mjs — write installer/src/_builddate.h.
//
// Issue #322: the inner PE build date is DERIVED from git, not hand-stamped.
// Each binary gets the last-commit date (committer, %cs) of its own input set
// — the exact file sets upload.mjs hashes for that binary (installer: src
// minus helper/ plus web/ plus the conf; helper: helper/), so the invariant
// "date moved ⇔ sha256 moved" is structural: same set, two functions.
// Shared inputs — installer.ico (both .res compilations consume it) and
// config/msys2-toolchain.json (a deliberate toolchain bump rebuilds both
// binaries; the installer-<date> component-tag namespace is date-keyed) — are
// in BOTH lists.
//
// Output (gitignored, regenerated by the Makefile's `dates` target and by
// syncGeneratedFiles.mjs at publish time):
//   #define CFG_BUILD_DATE_INSTALLER "2026-09-25"
//   #define CFG_BUILD_DATE_HELPER    "2026-09-25"
//
// platform.h maps these onto INSTALLER_BUILD_DATE; helper/version.rc and
// installer.rc include _builddate.h for their FileVersion/ProductVersion.
// Binary consumers of CFG_BUILD_DATE (self_update.c) read the INSTALLER date.

import {execSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');

/**
 * The date pathspecs, shared with the publish hash by construction.
 *
 * @param {string} root repo root (overridable for tests)
 * @returns {{helper: string[]; installer: string[]}}
 */
export function datePathspecs(root = ROOT) {
  const rel = (...segs) => path.join(root, ...segs);
  return {
    helper: [
      rel('installer', 'src', 'helper'),
      rel('installer', 'src', 'installer.ico'),
      rel('config', 'msys2-toolchain.json'),
    ],
    installer: [
      // installer/src minus helper/ (pathspec exclude magic) — the generated
      // trio (_config.h/_builddate.h/resources.h/script.built.js) is
      // gitignored, so git log cannot see it, matching the hash exclude.
      rel('installer', 'src'),
      ':(exclude)' + rel('installer', 'src', 'helper'),
      rel('installer', 'web'),
      rel('config', 'installer.conf'),
      rel('installer', 'src', 'installer.ico'),
      rel('config', 'msys2-toolchain.json'),
    ],
  };
}

/**
 * The environment for the git queries below, with the ambient git overlays
 * removed. Git exports GIT_DIR/GIT_INDEX_FILE/GIT_PREFIX into hooks (the
 * pre-push gate runs this tooling from the working tree it is pushing), and an
 * inherited GIT_DIR silently redirects a query aimed at one repository at
 * another one — with plausible-looking output, the worst kind of wrong.
 *
 * @returns {NodeJS.ProcessEnv}
 */
export function gitEnv() {
  const env = {...process.env};
  for (const key of [
    'GIT_DIR',
    'GIT_WORK_TREE',
    'GIT_INDEX_FILE',
    'GIT_PREFIX',
    'GIT_COMMON_DIR',
    'GIT_OBJECT_DIRECTORY',
    'GIT_ALTERNATE_OBJECT_DIRECTORIES',
  ]) {
    delete env[key];
  }
  return env;
}

/**
 * Refuse to derive anything from a shallow clone: a shallow clone does NOT
 * error on path-limited git log — it silently returns the grafted boundary
 * commit's date/epoch, which would bake a wrong (stale) value into the binaries
 * and the PE timestamp. Shared by the date and the epoch derivation.
 *
 * @param {string} root repo root
 */
export function assertFullHistory(root = ROOT) {
  const shallow = execSync('git rev-parse --is-shallow-repository', {
    cwd: root,
    encoding: 'utf-8',
    env: gitEnv(),
  }).trim();
  if (shallow === 'true') {
    throw new Error(
      'shallow clone — input-scoped git log would silently return wrong build dates; ' +
        'fetch full history (CI: fetch-depth: 0)'
    );
  }
}

/**
 * Last commit date (YYYY-MM-DD, committer %cs) touching any of the paths.
 *
 * @param {string[]} paths
 * @param {string} root
 * @returns {string}
 */
export function gitDate(paths, root = ROOT) {
  assertFullHistory(root);
  const out = execSync('git log -1 --format=%cs -- ' + paths.map(p => `"${p}"`).join(' '), {
    cwd: root,
    encoding: 'utf-8',
    env: gitEnv(),
  }).trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(out)) {
    throw new Error(
      `git log returned '${out}' — input-scoped history needs a full clone (CI: fetch-depth: 0)`
    );
  }
  return out;
}

/**
 * Both build dates. Exported for the unit tests.
 *
 * @param {string} root
 * @returns {{installer: string; helper: string}}
 */
export function buildDates(root = ROOT) {
  const specs = datePathspecs(root);
  return {
    installer: gitDate(specs.installer, root),
    helper: gitDate(specs.helper, root),
  };
}

/** The _builddate.h content for a given pair of dates. */
export function buildDateHeader(dates) {
  // FILEVERSION needs a numeric tuple (a,b,c,d) — windres cannot compute
  // 1,0,<YYYY>,<MMDD> from a string, so the generator derives it here.
  const tuple = date => {
    const [y, m, d] = date.split('-').map(Number);
    return `1,0,${y},${m * 100 + d}`;
  };
  const inst = tuple(dates.installer);
  const help = tuple(dates.helper);
  return [
    '// Auto-generated by tools/publish/generateBuildDates.mjs — do not edit.',
    '// Issue #322: per-binary git-derived build dates (last commit touching',
    "// each binary's input set — see the generator header for the lists).",
    '#ifndef BUILD_DATE_H',
    '#define BUILD_DATE_H',
    '',
    `#define CFG_BUILD_DATE_INSTALLER "${dates.installer}"`,
    `#define CFG_BUILD_DATE_HELPER "${dates.helper}"`,
    `#define CFG_BUILD_DATE_INSTALLER_STR "${dates.installer}\\0"`,
    `#define CFG_BUILD_DATE_HELPER_STR "${dates.helper}\\0"`,
    `#define CFG_BUILD_DATE_INSTALLER_V ${inst}`,
    `#define CFG_BUILD_DATE_HELPER_V ${help}`,
    '',
    '#endif /* BUILD_DATE_H */',
    '',
  ].join('\n');
}

export function main() {
  const dates = buildDates();
  const dst = path.join(ROOT, 'installer', 'src', '_builddate.h');
  const text = buildDateHeader(dates);
  const prev = fs.existsSync(dst) ? fs.readFileSync(dst, 'utf-8') : '';
  fs.writeFileSync(dst, text);
  // Only report when the content changed: the Makefile calls this on every
  // build, and a stable message keeps the build output readable.
  if (prev !== text) {
    console.log(`_builddate.h: installer ${dates.installer}, helper ${dates.helper}`);
  }
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  main();
}
